# revision 28250
# category Package
# catalog-ctan /fonts/ps-type1/cm-lgc
# catalog-date 2012-06-26 00:41:30 +0200
# catalog-license gpl
# catalog-version 0.5
Name:		texlive-cm-lgc
Version:	0.5
Release:	4
Summary:	Type 1 CM-based fonts for Latin, Greek and Cyrillic
Group:		Publishing
URL:		http://www.ctan.org/tex-archive/fonts/ps-type1/cm-lgc
License:	GPL
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/cm-lgc.tar.xz
Source1:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/cm-lgc.doc.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg
Requires(post):	texlive-kpathsea

%description
The fonts are converted from Metafont sources of the Computer
Modern font families, using textrace. Supported encodings are:
T1 (Latin), T2A (Cyrillic), LGR (Greek) and TS1. The package
also includes Unicode virtual fonts for use with Omega. The
font set is not a replacement for any of the other Computer
Modern-based font sets (for example, cm-super for Latin and
Cyrillic, or cbgreek for Greek), since it is available at a
single size only; it offers a compact set for 'general'
working. The fonts themselves are encoded to external
standards, and virtual fonts are provided for use with TeX.

%post
    %{_sbindir}/texlive.post

%postun
    if [ $1 -eq 0 ]; then
	%{_sbindir}/texlive.post
    fi

#-----------------------------------------------------------------------
%files
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmb6y.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmb6z.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmb8a.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmbc6y.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmbc6z.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmbc8a.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmbcce.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmbce.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmbcpg.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmbi6y.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmbi6z.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmbi8a.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmbice.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmbij6y.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmbij6z.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmbij8a.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmbijce.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmbijpg.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmbipg.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmbpg.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmr6y.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmr6z.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmr8a.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmrc6y.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmrc6z.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmrc8a.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmrcce.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmrce.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmrcpg.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmri6y.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmri6z.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmri8a.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmrice.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmrij6y.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmrij6z.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmrij8a.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmrijce.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmrijpg.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmripg.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcmrpg.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcsb6y.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcsb6z.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcsb8a.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcsbce.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcsbo6y.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcsbo6z.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcsbo8a.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcsboce.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcsbopg.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcsbpg.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcsr6y.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcsr6z.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcsr8a.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcsrce.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcsro6y.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcsro6z.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcsro8a.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcsroce.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcsropg.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fcsrpg.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fctr6y.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fctr6z.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fctr8a.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fctrc6y.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fctrc6z.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fctrc8a.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fctrcce.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fctrce.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fctrcpg.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fctri6y.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fctri6z.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fctri8a.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fctrice.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fctrij6y.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fctrij6z.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fctrij8a.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fctrijce.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fctrijpg.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fctripg.afm
%{_texmfdistdir}/fonts/afm/public/cm-lgc/fctrpg.afm
%{_texmfdistdir}/fonts/enc/dvips/cm-lgc/8r-mod.enc
%{_texmfdistdir}/fonts/map/dvips/cm-lgc/cm-lgc.map
%{_texmfdistdir}/fonts/ofm/public/cm-lgc/fcmbcut.ofm
%{_texmfdistdir}/fonts/ofm/public/cm-lgc/fcmbiut.ofm
%{_texmfdistdir}/fonts/ofm/public/cm-lgc/fcmbout.ofm
%{_texmfdistdir}/fonts/ofm/public/cm-lgc/fcmbut.ofm
%{_texmfdistdir}/fonts/ofm/public/cm-lgc/fcmbuut.ofm
%{_texmfdistdir}/fonts/ofm/public/cm-lgc/fcmrcut.ofm
%{_texmfdistdir}/fonts/ofm/public/cm-lgc/fcmriut.ofm
%{_texmfdistdir}/fonts/ofm/public/cm-lgc/fcmrout.ofm
%{_texmfdistdir}/fonts/ofm/public/cm-lgc/fcmrut.ofm
%{_texmfdistdir}/fonts/ofm/public/cm-lgc/fcmruut.ofm
%{_texmfdistdir}/fonts/ofm/public/cm-lgc/fcsbout.ofm
%{_texmfdistdir}/fonts/ofm/public/cm-lgc/fcsbut.ofm
%{_texmfdistdir}/fonts/ofm/public/cm-lgc/fcsrout.ofm
%{_texmfdistdir}/fonts/ofm/public/cm-lgc/fcsrut.ofm
%{_texmfdistdir}/fonts/ofm/public/cm-lgc/fctrcut.ofm
%{_texmfdistdir}/fonts/ofm/public/cm-lgc/fctriut.ofm
%{_texmfdistdir}/fonts/ofm/public/cm-lgc/fctrout.ofm
%{_texmfdistdir}/fonts/ofm/public/cm-lgc/fctrut.ofm
%{_texmfdistdir}/fonts/ofm/public/cm-lgc/fctruut.ofm
%{_texmfdistdir}/fonts/ovf/public/cm-lgc/fcmbcut.ovf
%{_texmfdistdir}/fonts/ovf/public/cm-lgc/fcmbiut.ovf
%{_texmfdistdir}/fonts/ovf/public/cm-lgc/fcmbout.ovf
%{_texmfdistdir}/fonts/ovf/public/cm-lgc/fcmbut.ovf
%{_texmfdistdir}/fonts/ovf/public/cm-lgc/fcmbuut.ovf
%{_texmfdistdir}/fonts/ovf/public/cm-lgc/fcmrcut.ovf
%{_texmfdistdir}/fonts/ovf/public/cm-lgc/fcmriut.ovf
%{_texmfdistdir}/fonts/ovf/public/cm-lgc/fcmrout.ovf
%{_texmfdistdir}/fonts/ovf/public/cm-lgc/fcmrut.ovf
%{_texmfdistdir}/fonts/ovf/public/cm-lgc/fcmruut.ovf
%{_texmfdistdir}/fonts/ovf/public/cm-lgc/fcsbout.ovf
%{_texmfdistdir}/fonts/ovf/public/cm-lgc/fcsbut.ovf
%{_texmfdistdir}/fonts/ovf/public/cm-lgc/fcsrout.ovf
%{_texmfdistdir}/fonts/ovf/public/cm-lgc/fcsrut.ovf
%{_texmfdistdir}/fonts/ovf/public/cm-lgc/fctrcut.ovf
%{_texmfdistdir}/fonts/ovf/public/cm-lgc/fctriut.ovf
%{_texmfdistdir}/fonts/ovf/public/cm-lgc/fctrout.ovf
%{_texmfdistdir}/fonts/ovf/public/cm-lgc/fctrut.ovf
%{_texmfdistdir}/fonts/ovf/public/cm-lgc/fctruut.ovf
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmb6a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmb6y.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmb6z.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmb7k.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmb7t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmb8a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmb8c.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmb8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmb8t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbc6a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbc6y.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbc6z.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbc7k.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbc7t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbc8a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbc8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbc8t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbcce.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbce.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbcgr.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbcpg.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbgr.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbi6a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbi6y.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbi6z.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbi7k.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbi7t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbi8a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbi8c.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbi8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbi8t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbice.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbigr.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbij8a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbij8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbipg.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbo6a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbo6y.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbo6z.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbo7k.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbo7t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbo8c.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbo8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbo8t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmboc8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmboce.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbogr.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbopg.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbpg.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbu6a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbu6y.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbu6z.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbu7k.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbu7t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbu8c.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbu8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbu8t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbuce.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbugr.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbuj8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmbupg.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmr6a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmr6y.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmr6z.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmr7k.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmr7t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmr8a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmr8c.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmr8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmr8t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmrc6a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmrc6y.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmrc6z.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmrc7k.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmrc7t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmrc8a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmrc8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmrc8t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmrcce.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmrce.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmrcgr.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmrcpg.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmrgr.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmri6a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmri6y.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmri6z.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmri7k.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmri7t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmri8a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmri8c.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmri8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmri8t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmrice.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmrigr.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmrij8a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmrij8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmripg.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmro6a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmro6y.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmro6z.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmro7k.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmro7t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmro8c.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmro8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmro8t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmroc8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmroce.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmrogr.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmropg.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmrpg.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmru6a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmru6y.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmru6z.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmru7k.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmru7t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmru8c.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmru8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmru8t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmruce.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmrugr.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmruj8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcmrupg.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsb6a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsb6y.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsb6z.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsb7k.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsb7t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsb8a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsb8c.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsb8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsb8t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsbce.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsbgr.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsbo6a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsbo6y.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsbo6z.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsbo7k.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsbo7t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsbo8a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsbo8c.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsbo8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsbo8t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsboce.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsbogr.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsbopg.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsbpg.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsr6a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsr6y.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsr6z.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsr7k.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsr7t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsr8a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsr8c.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsr8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsr8t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsrce.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsrgr.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsro6a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsro6y.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsro6z.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsro7k.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsro7t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsro8a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsro8c.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsro8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsro8t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsroce.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsrogr.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsropg.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fcsrpg.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctr6a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctr6y.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctr6z.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctr7k.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctr7t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctr8a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctr8c.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctr8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctr8t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctrc6a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctrc6y.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctrc6z.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctrc7k.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctrc7t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctrc8a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctrc8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctrc8t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctrcce.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctrce.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctrcgr.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctrcpg.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctrgr.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctri6a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctri6y.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctri6z.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctri7k.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctri7t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctri8a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctri8c.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctri8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctri8t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctrice.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctrigr.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctrij8a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctrij8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctripg.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctro6a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctro6y.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctro6z.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctro7k.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctro7t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctro8c.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctro8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctro8t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctroc8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctroce.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctrogr.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctropg.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctrpg.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctru6a.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctru6y.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctru6z.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctru7k.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctru7t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctru8c.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctru8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctru8t.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctruce.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctrugr.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctruj8r.tfm
%{_texmfdistdir}/fonts/tfm/public/cm-lgc/fctrupg.tfm
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmb6y.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmb6y.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmb6z.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmb6z.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmb8a.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmb8a.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbc6y.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbc6y.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbc6z.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbc6z.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbc8a.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbc8a.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbcce.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbcce.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbce.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbce.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbcpg.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbcpg.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbi6y.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbi6y.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbi6z.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbi6z.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbi8a.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbi8a.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbice.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbice.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbij6y.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbij6y.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbij6z.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbij6z.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbij8a.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbij8a.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbijce.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbijce.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbijpg.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbijpg.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbipg.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbipg.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbpg.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmbpg.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmr6y.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmr6y.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmr6z.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmr6z.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmr8a.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmr8a.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrc6y.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrc6y.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrc6z.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrc6z.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrc8a.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrc8a.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrcce.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrcce.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrce.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrce.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrcpg.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrcpg.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmri6y.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmri6y.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmri6z.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmri6z.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmri8a.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmri8a.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrice.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrice.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrij6y.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrij6y.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrij6z.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrij6z.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrij8a.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrij8a.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrijce.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrijce.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrijpg.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrijpg.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmripg.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmripg.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrpg.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcmrpg.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsb6y.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsb6y.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsb6z.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsb6z.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsb8a.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsb8a.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsbce.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsbce.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsbo6y.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsbo6y.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsbo6z.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsbo6z.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsbo8a.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsbo8a.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsboce.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsboce.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsbopg.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsbopg.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsbpg.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsbpg.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsr6y.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsr6y.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsr6z.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsr6z.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsr8a.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsr8a.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsrce.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsrce.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsro6y.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsro6y.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsro6z.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsro6z.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsro8a.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsro8a.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsroce.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsroce.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsropg.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsropg.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsrpg.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fcsrpg.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctr6y.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctr6y.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctr6z.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctr6z.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctr8a.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctr8a.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrc6y.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrc6y.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrc6z.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrc6z.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrc8a.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrc8a.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrcce.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrcce.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrce.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrce.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrcpg.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrcpg.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctri6y.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctri6y.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctri6z.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctri6z.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctri8a.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctri8a.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrice.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrice.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrij6y.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrij6y.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrij6z.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrij6z.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrij8a.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrij8a.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrijce.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrijce.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrijpg.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrijpg.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctripg.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctripg.pfb
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrpg.inf
%{_texmfdistdir}/fonts/type1/public/cm-lgc/fctrpg.pfb
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmb6a.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmb7k.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmb7t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmb8c.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmb8t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbc6a.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbc7k.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbc7t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbc8t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbcgr.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbgr.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbi6a.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbi7k.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbi7t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbi8c.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbi8t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbigr.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbo6a.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbo7k.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbo7t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbo8c.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbo8t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbogr.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbu6a.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbu7k.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbu7t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbu8c.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbu8t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmbugr.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmr6a.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmr7k.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmr7t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmr8c.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmr8t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmrc6a.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmrc7k.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmrc7t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmrc8t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmrcgr.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmrgr.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmri6a.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmri7k.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmri7t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmri8c.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmri8t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmrigr.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmro6a.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmro7k.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmro7t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmro8c.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmro8t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmrogr.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmru6a.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmru7k.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmru7t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmru8c.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmru8t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcmrugr.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsb6a.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsb7k.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsb7t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsb8c.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsb8t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsbgr.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsbo6a.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsbo7k.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsbo7t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsbo8c.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsbo8t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsbogr.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsr6a.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsr7k.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsr7t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsr8c.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsr8t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsrgr.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsro6a.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsro7k.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsro7t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsro8c.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsro8t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fcsrogr.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctr6a.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctr7k.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctr7t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctr8c.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctr8t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctrc6a.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctrc7k.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctrc7t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctrc8t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctrcgr.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctrgr.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctri6a.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctri7k.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctri7t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctri8c.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctri8t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctrigr.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctro6a.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctro7k.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctro7t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctro8c.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctro8t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctrogr.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctru6a.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctru7k.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctru7t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctru8c.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctru8t.vf
%{_texmfdistdir}/fonts/vf/public/cm-lgc/fctrugr.vf
%{_texmfdistdir}/tex/latex/cm-lgc/antcmlgc.sty
%{_texmfdistdir}/tex/latex/cm-lgc/cmlgc.sty
%{_texmfdistdir}/tex/latex/cm-lgc/lgrfcm.fd
%{_texmfdistdir}/tex/latex/cm-lgc/lgrfcs.fd
%{_texmfdistdir}/tex/latex/cm-lgc/lgrfct.fd
%{_texmfdistdir}/tex/latex/cm-lgc/ot1fcm.fd
%{_texmfdistdir}/tex/latex/cm-lgc/ot1fcs.fd
%{_texmfdistdir}/tex/latex/cm-lgc/ot1fct.fd
%{_texmfdistdir}/tex/latex/cm-lgc/ot2fcm.fd
%{_texmfdistdir}/tex/latex/cm-lgc/ot2fcs.fd
%{_texmfdistdir}/tex/latex/cm-lgc/ot2fct.fd
%{_texmfdistdir}/tex/latex/cm-lgc/t1fcm.fd
%{_texmfdistdir}/tex/latex/cm-lgc/t1fcs.fd
%{_texmfdistdir}/tex/latex/cm-lgc/t1fct.fd
%{_texmfdistdir}/tex/latex/cm-lgc/t2afcm.fd
%{_texmfdistdir}/tex/latex/cm-lgc/t2afcs.fd
%{_texmfdistdir}/tex/latex/cm-lgc/t2afct.fd
%{_texmfdistdir}/tex/latex/cm-lgc/ts1fcm.fd
%{_texmfdistdir}/tex/latex/cm-lgc/ts1fcs.fd
%{_texmfdistdir}/tex/latex/cm-lgc/ts1fct.fd
%{_texmfdistdir}/tex/latex/cm-lgc/ut1fcm.fd
%{_texmfdistdir}/tex/latex/cm-lgc/ut1fcs.fd
%{_texmfdistdir}/tex/latex/cm-lgc/ut1fct.fd
%doc %{_texmfdistdir}/doc/fonts/cm-lgc/COPYING
%doc %{_texmfdistdir}/doc/fonts/cm-lgc/HISTORY
%doc %{_texmfdistdir}/doc/fonts/cm-lgc/INSTALL
%doc %{_texmfdistdir}/doc/fonts/cm-lgc/README
%doc %{_texmfdistdir}/doc/fonts/cm-lgc/scripts.tar.gz

#-----------------------------------------------------------------------
%prep
%setup -c -a0 -a1

%build

%install
mkdir -p %{buildroot}%{_texmfdistdir}
cp -fpar fonts tex doc %{buildroot}%{_texmfdistdir}
